/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteIdeaCollaboratorUserArgs } from "./DeleteIdeaCollaboratorUserArgs";
import { IdeaCollaboratorUserFindManyArgs } from "./IdeaCollaboratorUserFindManyArgs";
import { IdeaCollaboratorUserFindUniqueArgs } from "./IdeaCollaboratorUserFindUniqueArgs";
import { IdeaCollaboratorUser } from "./IdeaCollaboratorUser";
import { IdeaCollaboratorUserService } from "../ideaCollaboratorUser.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => IdeaCollaboratorUser)
export class IdeaCollaboratorUserResolverBase {
  constructor(
    protected readonly service: IdeaCollaboratorUserService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "IdeaCollaboratorUser",
    action: "read",
    possession: "any",
  })
  async _ideaCollaboratorUsersMeta(
    @graphql.Args() args: IdeaCollaboratorUserFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [IdeaCollaboratorUser])
  @nestAccessControl.UseRoles({
    resource: "IdeaCollaboratorUser",
    action: "read",
    possession: "any",
  })
  async ideaCollaboratorUsers(
    @graphql.Args() args: IdeaCollaboratorUserFindManyArgs
  ): Promise<IdeaCollaboratorUser[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => IdeaCollaboratorUser, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "IdeaCollaboratorUser",
    action: "read",
    possession: "own",
  })
  async ideaCollaboratorUser(
    @graphql.Args() args: IdeaCollaboratorUserFindUniqueArgs
  ): Promise<IdeaCollaboratorUser | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => IdeaCollaboratorUser)
  @nestAccessControl.UseRoles({
    resource: "IdeaCollaboratorUser",
    action: "delete",
    possession: "any",
  })
  async deleteIdeaCollaboratorUser(
    @graphql.Args() args: DeleteIdeaCollaboratorUserArgs
  ): Promise<IdeaCollaboratorUser | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
