/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { DigitalCustodianAgentService } from "../digitalCustodianAgent.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DigitalCustodianAgentCreateInput } from "./DigitalCustodianAgentCreateInput";
import { DigitalCustodianAgentWhereInput } from "./DigitalCustodianAgentWhereInput";
import { DigitalCustodianAgentWhereUniqueInput } from "./DigitalCustodianAgentWhereUniqueInput";
import { DigitalCustodianAgentFindManyArgs } from "./DigitalCustodianAgentFindManyArgs";
import { DigitalCustodianAgentUpdateInput } from "./DigitalCustodianAgentUpdateInput";
import { DigitalCustodianAgent } from "./DigitalCustodianAgent";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class DigitalCustodianAgentControllerBase {
  constructor(
    protected readonly service: DigitalCustodianAgentService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: DigitalCustodianAgent })
  @nestAccessControl.UseRoles({
    resource: "DigitalCustodianAgent",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: DigitalCustodianAgentCreateInput,
  })
  async create(
    @common.Body() data: DigitalCustodianAgentCreateInput
  ): Promise<DigitalCustodianAgent> {
    return await this.service.create({
      data: {
        ...data,

        MyAiGatekeeper: data.MyAiGatekeeper
          ? {
              connect: data.MyAiGatekeeper,
            }
          : undefined,
      },
      select: {
        agentStatus: true,
        createdAt: true,
        id: true,
        lastActiveTime: true,
        lastError: true,

        MyAiGatekeeper: {
          select: {
            id: true,
          },
        },

        tasksCompleted: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [DigitalCustodianAgent] })
  @ApiNestedQuery(DigitalCustodianAgentFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "DigitalCustodianAgent",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(
    @common.Req() request: Request
  ): Promise<DigitalCustodianAgent[]> {
    const args = plainToClass(DigitalCustodianAgentFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        agentStatus: true,
        createdAt: true,
        id: true,
        lastActiveTime: true,
        lastError: true,

        MyAiGatekeeper: {
          select: {
            id: true,
          },
        },

        tasksCompleted: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: DigitalCustodianAgent })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DigitalCustodianAgent",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: DigitalCustodianAgentWhereUniqueInput
  ): Promise<DigitalCustodianAgent | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        agentStatus: true,
        createdAt: true,
        id: true,
        lastActiveTime: true,
        lastError: true,

        MyAiGatekeeper: {
          select: {
            id: true,
          },
        },

        tasksCompleted: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: DigitalCustodianAgent })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DigitalCustodianAgent",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: DigitalCustodianAgentUpdateInput,
  })
  async update(
    @common.Param() params: DigitalCustodianAgentWhereUniqueInput,
    @common.Body() data: DigitalCustodianAgentUpdateInput
  ): Promise<DigitalCustodianAgent | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          MyAiGatekeeper: data.MyAiGatekeeper
            ? {
                connect: data.MyAiGatekeeper,
              }
            : undefined,
        },
        select: {
          agentStatus: true,
          createdAt: true,
          id: true,
          lastActiveTime: true,
          lastError: true,

          MyAiGatekeeper: {
            select: {
              id: true,
            },
          },

          tasksCompleted: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: DigitalCustodianAgent })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DigitalCustodianAgent",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: DigitalCustodianAgentWhereUniqueInput
  ): Promise<DigitalCustodianAgent | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          agentStatus: true,
          createdAt: true,
          id: true,
          lastActiveTime: true,
          lastError: true,

          MyAiGatekeeper: {
            select: {
              id: true,
            },
          },

          tasksCompleted: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
