/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, ValidateNested, IsOptional } from "class-validator";
import { AiGatekeeperCreateNestedManyWithoutUsersInput } from "./AiGatekeeperCreateNestedManyWithoutUsersInput";
import { Type } from "class-transformer";
import { IsJSONValue } from "@app/custom-validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { IdeaCollaboratorDevCreateNestedManyWithoutUsersInput } from "./IdeaCollaboratorDevCreateNestedManyWithoutUsersInput";

@InputType()
class UserCreateInput {
  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  company!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  email!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  firstName!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  lastName!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  location!: string;

  @ApiProperty({
    required: false,
    type: () => AiGatekeeperCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => AiGatekeeperCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => AiGatekeeperCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  ownership?: AiGatekeeperCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  password!: string;

  @ApiProperty({
    required: true,
  })
  @IsJSONValue()
  @Field(() => GraphQLJSON)
  roles!: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => IdeaCollaboratorDevCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => IdeaCollaboratorDevCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => IdeaCollaboratorDevCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  teamOwner?: IdeaCollaboratorDevCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  username!: string;
}

export { UserCreateInput as UserCreateInput };
