/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteIdeaViewerGuestArgs } from "./DeleteIdeaViewerGuestArgs";
import { IdeaViewerGuestFindManyArgs } from "./IdeaViewerGuestFindManyArgs";
import { IdeaViewerGuestFindUniqueArgs } from "./IdeaViewerGuestFindUniqueArgs";
import { IdeaViewerGuest } from "./IdeaViewerGuest";
import { IdeaViewerGuestService } from "../ideaViewerGuest.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => IdeaViewerGuest)
export class IdeaViewerGuestResolverBase {
  constructor(
    protected readonly service: IdeaViewerGuestService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "IdeaViewerGuest",
    action: "read",
    possession: "any",
  })
  async _ideaViewerGuestsMeta(
    @graphql.Args() args: IdeaViewerGuestFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [IdeaViewerGuest])
  @nestAccessControl.UseRoles({
    resource: "IdeaViewerGuest",
    action: "read",
    possession: "any",
  })
  async ideaViewerGuests(
    @graphql.Args() args: IdeaViewerGuestFindManyArgs
  ): Promise<IdeaViewerGuest[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => IdeaViewerGuest, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "IdeaViewerGuest",
    action: "read",
    possession: "own",
  })
  async ideaViewerGuest(
    @graphql.Args() args: IdeaViewerGuestFindUniqueArgs
  ): Promise<IdeaViewerGuest | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => IdeaViewerGuest)
  @nestAccessControl.UseRoles({
    resource: "IdeaViewerGuest",
    action: "delete",
    possession: "any",
  })
  async deleteIdeaViewerGuest(
    @graphql.Args() args: DeleteIdeaViewerGuestArgs
  ): Promise<IdeaViewerGuest | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
