/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { UserService } from "../user.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { UserCreateInput } from "./UserCreateInput";
import { UserWhereInput } from "./UserWhereInput";
import { UserWhereUniqueInput } from "./UserWhereUniqueInput";
import { UserFindManyArgs } from "./UserFindManyArgs";
import { UserUpdateInput } from "./UserUpdateInput";
import { User } from "./User";
import { AiGatekeeperFindManyArgs } from "../../aiGatekeeper/base/AiGatekeeperFindManyArgs";
import { AiGatekeeper } from "../../aiGatekeeper/base/AiGatekeeper";
import { AiGatekeeperWhereUniqueInput } from "../../aiGatekeeper/base/AiGatekeeperWhereUniqueInput";
import { IdeaCollaboratorDevFindManyArgs } from "../../ideaCollaboratorDev/base/IdeaCollaboratorDevFindManyArgs";
import { IdeaCollaboratorDev } from "../../ideaCollaboratorDev/base/IdeaCollaboratorDev";
import { IdeaCollaboratorDevWhereUniqueInput } from "../../ideaCollaboratorDev/base/IdeaCollaboratorDevWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class UserControllerBase {
  constructor(
    protected readonly service: UserService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: User })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: UserCreateInput,
  })
  async create(@common.Body() data: UserCreateInput): Promise<User> {
    return await this.service.create({
      data: data,
      select: {
        company: true,
        createdAt: true,
        email: true,
        firstName: true,
        id: true,
        lastName: true,
        location: true,
        roles: true,
        updatedAt: true,
        username: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [User] })
  @ApiNestedQuery(UserFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(@common.Req() request: Request): Promise<User[]> {
    const args = plainToClass(UserFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        company: true,
        createdAt: true,
        email: true,
        firstName: true,
        id: true,
        lastName: true,
        location: true,
        roles: true,
        updatedAt: true,
        username: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        company: true,
        createdAt: true,
        email: true,
        firstName: true,
        id: true,
        lastName: true,
        location: true,
        roles: true,
        updatedAt: true,
        username: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: UserUpdateInput,
  })
  async update(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() data: UserUpdateInput
  ): Promise<User | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          company: true,
          createdAt: true,
          email: true,
          firstName: true,
          id: true,
          lastName: true,
          location: true,
          roles: true,
          updatedAt: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          company: true,
          createdAt: true,
          email: true,
          firstName: true,
          id: true,
          lastName: true,
          location: true,
          roles: true,
          updatedAt: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/ownership")
  @ApiNestedQuery(AiGatekeeperFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "AiGatekeeper",
    action: "read",
    possession: "any",
  })
  async findManyOwnership(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<AiGatekeeper[]> {
    const query = plainToClass(AiGatekeeperFindManyArgs, request.query);
    const results = await this.service.findOwnership(params.id, {
      ...query,
      select: {
        AIStatus: true,
        createdAt: true,

        createdBy: {
          select: {
            id: true,
          },
        },

        id: true,
        roles: true,
        TasksCompleted: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/ownership")
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "update",
    possession: "any",
  })
  async connectOwnership(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: AiGatekeeperWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      ownership: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/ownership")
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "update",
    possession: "any",
  })
  async updateOwnership(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: AiGatekeeperWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      ownership: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/ownership")
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "update",
    possession: "any",
  })
  async disconnectOwnership(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: AiGatekeeperWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      ownership: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/teamOwner")
  @ApiNestedQuery(IdeaCollaboratorDevFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "IdeaCollaboratorDev",
    action: "read",
    possession: "any",
  })
  async findManyTeamOwner(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<IdeaCollaboratorDev[]> {
    const query = plainToClass(IdeaCollaboratorDevFindManyArgs, request.query);
    const results = await this.service.findTeamOwner(params.id, {
      ...query,
      select: {
        createdAt: true,
        email: true,
        id: true,

        inATeam: {
          select: {
            id: true,
          },
        },

        location: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/teamOwner")
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "update",
    possession: "any",
  })
  async connectTeamOwner(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: IdeaCollaboratorDevWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      teamOwner: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/teamOwner")
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "update",
    possession: "any",
  })
  async updateTeamOwner(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: IdeaCollaboratorDevWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      teamOwner: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/teamOwner")
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "update",
    possession: "any",
  })
  async disconnectTeamOwner(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: IdeaCollaboratorDevWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      teamOwner: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
