/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { IdeaCollaboratorDevService } from "../ideaCollaboratorDev.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { IdeaCollaboratorDevCreateInput } from "./IdeaCollaboratorDevCreateInput";
import { IdeaCollaboratorDevWhereInput } from "./IdeaCollaboratorDevWhereInput";
import { IdeaCollaboratorDevWhereUniqueInput } from "./IdeaCollaboratorDevWhereUniqueInput";
import { IdeaCollaboratorDevFindManyArgs } from "./IdeaCollaboratorDevFindManyArgs";
import { IdeaCollaboratorDevUpdateInput } from "./IdeaCollaboratorDevUpdateInput";
import { IdeaCollaboratorDev } from "./IdeaCollaboratorDev";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class IdeaCollaboratorDevControllerBase {
  constructor(
    protected readonly service: IdeaCollaboratorDevService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: IdeaCollaboratorDev })
  @nestAccessControl.UseRoles({
    resource: "IdeaCollaboratorDev",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: IdeaCollaboratorDevCreateInput,
  })
  async create(
    @common.Body() data: IdeaCollaboratorDevCreateInput
  ): Promise<IdeaCollaboratorDev> {
    return await this.service.create({
      data: {
        ...data,

        inATeam: data.inATeam
          ? {
              connect: data.inATeam,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        email: true,
        id: true,

        inATeam: {
          select: {
            id: true,
          },
        },

        location: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [IdeaCollaboratorDev] })
  @ApiNestedQuery(IdeaCollaboratorDevFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "IdeaCollaboratorDev",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(
    @common.Req() request: Request
  ): Promise<IdeaCollaboratorDev[]> {
    const args = plainToClass(IdeaCollaboratorDevFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        email: true,
        id: true,

        inATeam: {
          select: {
            id: true,
          },
        },

        location: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: IdeaCollaboratorDev })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "IdeaCollaboratorDev",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: IdeaCollaboratorDevWhereUniqueInput
  ): Promise<IdeaCollaboratorDev | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        email: true,
        id: true,

        inATeam: {
          select: {
            id: true,
          },
        },

        location: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: IdeaCollaboratorDev })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "IdeaCollaboratorDev",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: IdeaCollaboratorDevUpdateInput,
  })
  async update(
    @common.Param() params: IdeaCollaboratorDevWhereUniqueInput,
    @common.Body() data: IdeaCollaboratorDevUpdateInput
  ): Promise<IdeaCollaboratorDev | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          inATeam: data.inATeam
            ? {
                connect: data.inATeam,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          email: true,
          id: true,

          inATeam: {
            select: {
              id: true,
            },
          },

          location: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: IdeaCollaboratorDev })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "IdeaCollaboratorDev",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: IdeaCollaboratorDevWhereUniqueInput
  ): Promise<IdeaCollaboratorDev | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          email: true,
          id: true,

          inATeam: {
            select: {
              id: true,
            },
          },

          location: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
